# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

# Brews (Packages)
brew "bat"
brew "unbound"
brew "gnutls"
brew "cask"
brew "exa"
brew "fnm"
brew "fontconfig"
brew "fzf"
brew "git"
brew "groonga"
brew "htop"
brew "httpie"
brew "node"
brew "pandoc"
brew "jupyterlab"
brew "mariadb", restart_service: true
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "python-tk@3.9"
brew "ranger"
brew "trash-cli"
brew "vim"
brew "wget"
brew "zoxide"

# Casks (Applications)
cask "alfred"
cask "font-hack-nerd-font"
cask "iterm2"
cask "kitty"
cask "visual-studio-code"
